### ISSUE TITLE
Qt build segfaults in debug mode

### ISSUE THREAD

**Issue by OFFTKP** [wheremyfoodat/Panda3DS#389]
Build Qt build in debug mode (not relwithdebinfo)
Asserts are now enabled
An assert fails at:
```
#5  0x0000555555776232 in Zep::ZepMode::GetCurrentWindow() const (this=0x555557bb4c10) at /home/offtkp/other/Panda3DS/third_party/zep/include/../src/mode.cpp:163
#6  0x0000555555767300 in Zep::ZepEditor::SetGlobalMode(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x5555576615c0, currentMode="Standard")
    at /home/offtkp/other/Panda3DS/third_party/zep/include/../src/editor.cpp:786
#7  0x00005555558604fc in TextEditorWindow::TextEditorWindow(QWidget*, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) (this=0x5555579131b0, parent=0x7fffffffd8a0, filename="script.lua", initialText="")
```

**Comment by wheremyfoodat** [comment]
Fixes in latest commit
